apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-client-configmap
  namespace: {{ .Values.app.namespace }}
data:
  package.json: |
    {
        "name": "client",
        "version": "0.1.0",
        "private": true,
        "dependencies": {
            "axios": "^0.18.0",
            "bootstrap": "^4.3.1",
            "react": "^16.8.6",
            "react-dom": "^16.8.6",
            "react-router-dom": "^5.0.0",
            "react-scripts": "3.0.1",
            "react-table": "^6.10.0",
            "styled-components": "^4.2.0"
        },
        "scripts": {
            "start": "PORT=8000 react-scripts start",
            "build": "react-scripts build",
            "test": "react-scripts test",
            "eject": "react-scripts eject"
        },
        "eslintConfig": {
            "extends": "react-app"
        },
        "browserslist": {
            "production": [
                ">0.2%",
                "not dead",
                "not op_mini all"
            ],
            "development": [
                "last 1 chrome version",
                "last 1 firefox version",
                "last 1 safari version"
            ]
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-server-configmap
  namespace: {{ .Values.app.namespace }}
data:
  package.json: |
    {
      "name": "server",
      "version": "1.0.0",
      "main": "index.js",
      "license": "MIT",
      "dependencies": {
        "body-parser": "^1.19.0",
        "cors": "^2.8.5",
        "express": "^4.16.4",
        "mongoose": "^6.5.0"
      }
    }
