apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.front.name }}-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.backIngress }}"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.frontIngress }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service: 
            name: {{ .Values.front.name }}-dns-svc
            port: 
              number: {{ .Values.front.svc.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.back.name }}-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin:  "{{ .Values.ingress.frontIngress }}"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.backIngress }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.back.name }}-dns-svc
            port:
              number: {{ .Values.back.svc.port }}
