apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}-dns-svc
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.front.svc.port }}
    targetPort: {{ .Values.front.svc.port }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}-dns-svc
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.back.svc.port }}
    targetPort: {{ .Values.back.svc.port }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-svc
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
